services:
  - type: static
    name: myhealthkey
    env: static
    buildCommand: npm ci || npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: RENDER_NODE_VERSION
        value: "18"
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
